### ISSUE TITLE
Mix and Match is broken

### ISSUE THREAD

**Issue by scottkunkel** [rayxuln/spine-runtime-for-godot#12]
this will crash on 
[0] ???
[1] SpineSprite::update_mesh_from_skeleton (C:\Projects\godot\modules\spine_runtime\SpineSprite.cpp:342)

```
	var hair: SpineSkin = spine_sprite.get_skeleton().get_data().find_skin("hair/brown")
	var at = hair.get_attachments()
	while at.has_next():
		var at1 = at.next()
		print(at1.get_attachment().get_attachment_name())
	spine_sprite.get_skeleton().set_skin(hair)
```

[CustomSkinProject.zip](https://github.com/rayxuln/spine-runtime-for-godot/files/4906716/CustomSkinProject.zip)

**Comment by rayxuln** [comment]
The code works fine in my godot build. I don't know if this issue is a random bug...

**Comment by Jonchun** [comment]
Doesn't crash for me either.

![image](https://user-images.githubusercontent.com/5800539/87224553-27c34800-c354-11ea-9061-39db37856bb7.png)

**Comment by scottkunkel** [comment]
works now
