### ISSUE TITLE
[Feature] Change default skin in editor

### ISSUE THREAD

**Issue by Jonchun** [rayxuln/spine-runtime-for-godot#13]
If the `default` skin is blank (such as in the mix and match example) http://esotericsoftware.com/spine-examples-mix-and-match, you don't see anything in the editor. Would like a way to set the skin that the editor loads.

I think this would make the most sense as a string property on `SpineSprite`.

**Comment by rayxuln** [comment]
I added a field, "Packed Skin Resource" to SpineSprite class. You can custom the SpineSprite's skin by setting the sub skin names in the "Packed Skin Resource". The skeleton skin is set whenever this resource changes. The example project is updated, too.

**Comment by Jonchun** [comment]
Works perfectly. You're amazing! This is even more than I was expecting.
