### ISSUE TITLE
SpineEvent methods crashes godot

### ISSUE THREAD

**Issue by Jonchun** [rayxuln/spine-runtime-for-godot#16]
Trying to do anything with a `SpineEvent` seems to crash Godot. 
```
func _on_SpineSprite_animation_complete(_animation_state: SpineAnimationState, _track_entry: SpineTrackEntry, _event: SpineEvent):
	print(_event.get_data())
	print(_event.get_event_name())
```

**Comment by scottkunkel** [comment]
No sure what you are trying to do.

Only EventType_Event has an actual event associated with it, otherwise _event is null.

so this works:

```
func test6()->void:
	$SpineSprite.connect("animation_complete", self, "done");
	$SpineSprite.get_animation_state().set_animation("dance", false, 0);

func done(a,b,c)->void:
	print("Done")
```

**Comment by scottkunkel** [comment]
It should be possible in code to add events to the callbacks, though. Need to discuss usage.
I'd say go for it since otherwise godot crashes on calling a method on a null object.

**Comment by Jonchun** [comment]
I'm not actually using the SpineEvent, but I'm documenting the fact that trying to do anything with the SpineEvent crashes.

I'm not getting a null value for parameter `c`, I'm getting a `SpineEvent` object.
![image](https://user-images.githubusercontent.com/5800539/87353383-a8d43800-c52a-11ea-874a-8eb94746e045.png)

However, if I try to call any method on it other than just printing it, Godot crashes.

**Comment by rayxuln** [comment]
I fixed it.

Now the SpineEvent you got should be NULL in "animation_complete".

It crashed because the actual spine object is NULL.
