### ISSUE TITLE
[Bug] Setting skin resource from code

### ISSUE THREAD

**Issue by yuraj11** [rayxuln/spine-runtime-for-godot#17]
Calling this when skin skin resource is already set:
```
spine.animation_state_data_res = load(type)
spine.packed_skin_resource = load(skin)
```
causes this issue in logs:
```
connect: Signal 'property_changed' is already connected to given method '_on_skin_property_changed' in that object.
```

**Comment by scottkunkel** [comment]
We can disconnect the signal before assigning the new skin.
Alternatively, we can set the skin, not do the signal connection when a skin was already there and trigger the signal in the c code itself.

@rayxuln  What is the purpose of the signal? The skin will not change by itself but has to be assigned manually, meaning the programmer can run the signal itself.

**Comment by rayxuln** [comment]
It's for noticing the SpineSprite to change the skin when the user changed the skin names in the packed skin resources in the editor.

Don't know why this error happened, but it's not fetal.

I'll fix it later.

**Comment by scottkunkel** [comment]
You just need to disconnect signal from the old skin if it’s there.

Thomas

**Comment by scottkunkel** [comment]
If that signal is needed, then my pr did it wrong by removing it entirely.

Thomas

**Comment by yuraj11** [comment]
Thanks. Fixed!
