### ISSUE TITLE
Material shader is not working

### ISSUE THREAD

**Issue by yuraj11** [rayxuln/spine-runtime-for-godot#19]
Setting custom material shader on SpineSprite is not working (nothing happens).

**Comment by scottkunkel** [comment]
If you want to set a special shader such as an outline for the whole figure, you’ll have to create a viewport/ camera combo and apply the shader to that. It’s more involved.

Thomas

**Comment by yuraj11** [comment]
OK I will try it with the viewport thing. Thanks for the info.

**Comment by scottkunkel** [comment]
I’d go back and check how gdquest did it in his battlers in his openrpg projects.

Thomas
