### ISSUE TITLE
The selected resource (SpineSkeletonJsonDataResource) does not match any type expected for this property (SpineAnimationStateDataResource).

### ISSUE THREAD

**Issue by pegasusearl** [rayxuln/spine-runtime-for-godot#23]
I tried to export with either binary and json but still not working.
I export with default settings + packing atlas. I'm using spine 3.8.97 ESS

![04_04-03-35_843](https://user-images.githubusercontent.com/23167087/92167121-11bd9980-ee64-11ea-9ef9-4010ce7692ac.png)

**Comment by rayxuln** [comment]
Did you assign a SpineSkeletonJsonDataResource type resource to a SpineAnimationStateDataResource type property?

**Comment by pegasusearl** [comment]
eeeeeh... I thought that thing means the spine json file. ah sorry my bad. Now I found the way to use it. Thank you for the module sir.

one more question
> Compiling godot for debug (-Od flag) will severely impact performance Compile with -O2 flag for godot engine and run linker
> can double fps
But how do I input the flag?

**Comment by rayxuln** [comment]
You can learn the details from https://docs.godotengine.org/en/stable/development/cpp/binding_to_external_libraries.html

**Comment by scottkunkel** [comment]
You don’t have to worry about this. The spine component gets compiled with the right flags. It’s overwriting the defaults.

Thomas
