### ISSUE TITLE
Bounding boxes support

### ISSUE THREAD

**Issue by yuraj11** [rayxuln/spine-runtime-for-godot#25]
Does this runtime support this feature or do you plan to add this feature? For example check precise hit detection:
http://esotericsoftware.com/spine-bounding-boxes

https://github.com/rayxuln/spine-runtime-for-godot/blob/9166bf9ea62df6968dd8bcf1202867b896982fef/spine-cpp/src/spine/SkeletonBounds.cpp

**Comment by yuraj11** [comment]
OK I have workaround for this - just use bind slots and collision shapes.

**Comment by rayxuln** [comment]
I don't know if the bounding boxes of spine is useful in godot.
