### ISSUE TITLE
Better instructions on how to use are needed

### ISSUE THREAD

**Issue by jeudy-ua** [rayxuln/spine-runtime-for-godot#32]
Can you please add some instructions on how to start using the module from scratch?

I'm starting a new project, added the SpineSprite, imported the .atlas and .json files exported from Spine, but nothing is happening. I don't see the options seen on the video you posted on reddit.

I compiled Godot from the 3.x branch with your module on the 3.8 branch.

The exported animation from spine was exported from Spine 3.8.

This is the most promising and up to date integration for Godot, so would really appreciate the basic instructions.

**Comment by rayxuln** [comment]
The spine 3.8 branch is not updated yet, you could try spine4.0 to use the new functions. I'll update the spine 3.8 branch as soon as possible.

**Comment by jeudy-ua** [comment]
That'd be amazing! if I switch to the spine3.8 branch and try to import the project, I get this error:

![image](https://user-images.githubusercontent.com/43071525/128589186-895edb64-0243-46ff-9f5e-1bc5f121ec6f.png)

**Comment by rayxuln** [comment]
I've update the code and the example project on spine3.8 branch, now it should have the same features/functions as the spine4.0 branch.

Check it out!

**Comment by rayxuln** [comment]
> That'd be amazing! if I switch to the spine3.8 branch and try to import the project, I get this error:
> 
> ![image](https://user-images.githubusercontent.com/43071525/128589186-895edb64-0243-46ff-9f5e-1bc5f121ec6f.png)

It's ok, just ignore it, and open other scene in the example project.

As long as godot does not crash, it'll be fine.......

**Comment by jeudy-ua** [comment]
Importing from the spine3.8 branch works fine. Need to ignore the Test1.tscn error and pick a different one.

Thanks for the reply.

**Comment by rayxuln** [comment]
I've added instructions in the repo wiki. You can learn how to use the features/functions from it.
