### ISSUE TITLE
Error with building project

### ISSUE THREAD

**Issue by hmental** [rayxuln/spine-runtime-for-godot#36]
Hi,

First, thanks for creating runtime! In editor everything works great but I have problem after exporting project to Windows.
After export, when I try to open exe I see this error:
ERROR: Cannot get class 'SpineSkeletonJsonDataResource'.

I need add some dll to folder? Set something in project settings in godot to build with yours module?

Thanks,
hmental.

**Comment by scottkunkel** [comment]
Did you build the template for windows as well?

Thomas

**Comment by hmental** [comment]
Nope, I download templates from here: https://downloads.tuxfamily.org/godotengine/3.4/beta4/
So I need manualy build templates, yup?

**Comment by scottkunkel** [comment]
Correct, the templates also need to include the spine code. So in addition to the editor, you’ll need to build the templates as well


Thomas

**Comment by hmental** [comment]
Okay, as I think about it now it's actually obvious ;p
Thanks a lot for your help!

**Comment by hmental** [comment]
Everything works, thanks again for your help ;]

**Comment by scottkunkel** [comment]
You’re very welcome

Thomas
