### ISSUE TITLE
Clipping is not working

### ISSUE THREAD

**Issue by rayxuln** [rayxuln/spine-runtime-for-godot#4]

**Comment by scottkunkel** [comment]
Please explain.

**Comment by rayxuln** [comment]
The animation "portal" in SpineBoy is not the same as expected when played using this runtime module in Godot.

**Comment by scottkunkel** [comment]
Tricky. Looking at the example, the SpineSprite is only available when inside a clipping mesh.
Godot is not really supporting clipping masks. I found two ways of doing this:
- https://godotengine.org/qa/3031/how-do-i-mask-a-sprite Lightmask using a texture
- Shader which would have to look at the mesh and set alpha according to the pixel position

The last one seems to be the better solution, however, it will prevent other shaders on the SpineSprite. I can see this working with another option on the SpineSprite object to enable/ disable it.

**Comment by scottkunkel** [comment]
Actually scrap that. Looking at https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-cocos2dx/src/spine/SkeletonRenderer.cpp, clipping can be done by eliminating vertices from the attachments using the runtime SkeletonClipping class. Gotta dig deeper.

**Comment by rayxuln** [comment]
Nailed it.

Next is to test its stability.
